
export const supabaseUrl = 'https://gamzjdoabdgiucnklpto.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbXpqZG9hYmRnaXVjbmtscHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjU4NjUsImV4cCI6MjA1NTY0MTg2NX0.gtjtRrRodTDrr_goOBWNzhzLcLoVAgj1OUjeRfhtDnY';